# Generated by Django 4.2.2 on 2023-08-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caloriass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pao', models.IntegerField(default=0)),
                ('milho', models.IntegerField(default=0)),
                ('arroz', models.IntegerField(default=0)),
                ('ovo', models.IntegerField(default=0)),
                ('peixe', models.IntegerField(default=0)),
                ('bife', models.IntegerField(default=0)),
                ('chocolate', models.IntegerField(default=0)),
                ('sorvete', models.IntegerField(default=0)),
                ('bombom', models.IntegerField(default=0)),
                ('tipo', models.IntegerField(default=0)),
                ('atual', models.CharField(default='nulo', max_length=50)),
            ],
        ),
    ]
